package com.frost23z.bookshelf.ui.theme.colorscheme

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

/**
 * Color scheme for Emerald theme.
 * Used Primary Color: #50C878 with true to color inputs.
 * M3 colors generated by Material Theme Builder (https://goo.gle/material-theme-builder-web)
 */

internal object EmeraldColorScheme : ColorSchemeController() {
    override val darkScheme =
        darkColorScheme(
            primary = Color(0xFF74EB97),
            onPrimary = Color(0xFF003919),
            primaryContainer = Color(0xFF47C071),
            onPrimaryContainer = Color(0xFF00260E),
            secondary = Color(0xFFA3D2AA),
            onSecondary = Color(0xFF0C381C),
            secondaryContainer = Color(0xFF1E482B),
            onSecondaryContainer = Color(0xFFB1E0B8),
            tertiary = Color(0xFFAFD9FF),
            onTertiary = Color(0xFF003350),
            tertiaryContainer = Color(0xFF52B3F7),
            onTertiaryContainer = Color(0xFF002338),
            error = Color(0xFFFFB4AB),
            onError = Color(0xFF690005),
            errorContainer = Color(0xFF93000A),
            onErrorContainer = Color(0xFFFFDAD6),
            background = Color(0xFF0F150F),
            onBackground = Color(0xFFDEE4DB),
            surface = Color(0xFF0F150F),
            onSurface = Color(0xFFDEE4DB),
            surfaceVariant = Color(0xFF3E4A3F),
            onSurfaceVariant = Color(0xFFBDCABC),
            outline = Color(0xFF879487),
            outlineVariant = Color(0xFF3E4A3F),
            scrim = Color(0xFF000000),
            inverseSurface = Color(0xFFDEE4DB),
            inverseOnSurface = Color(0xFF2B322C),
            inversePrimary = Color(0xFF006D36),
            surfaceDim = Color(0xFF0F150F),
            surfaceBright = Color(0xFF343B34),
            surfaceContainerLowest = Color(0xFF09100A),
            surfaceContainerLow = Color(0xFF171D17),
            surfaceContainer = Color(0xFF1B211B),
            surfaceContainerHigh = Color(0xFF252C25),
            surfaceContainerHighest = Color(0xFF303630)
        )

    override val lightScheme =
        lightColorScheme(
            primary = Color(0xFF006D36),
            onPrimary = Color(0xFFFFFFFF),
            primaryContainer = Color(0xFF5BD381),
            onPrimaryContainer = Color(0xFF003718),
            secondary = Color(0xFF3D6747),
            onSecondary = Color(0xFFFFFFFF),
            secondaryContainer = Color(0xFFC0F0C7),
            onSecondaryContainer = Color(0xFF285233),
            tertiary = Color(0xFF006496),
            onTertiary = Color(0xFFFFFFFF),
            tertiaryContainer = Color(0xFF77C3FF),
            onTertiaryContainer = Color(0xFF00324E),
            error = Color(0xFFBA1A1A),
            onError = Color(0xFFFFFFFF),
            errorContainer = Color(0xFFFFDAD6),
            onErrorContainer = Color(0xFF410002),
            background = Color(0xFFF5FBF1),
            onBackground = Color(0xFF171D17),
            surface = Color(0xFFF5FBF1),
            onSurface = Color(0xFF171D17),
            surfaceVariant = Color(0xFFD9E6D7),
            onSurfaceVariant = Color(0xFF3E4A3F),
            outline = Color(0xFF6E7A6E),
            outlineVariant = Color(0xFFBDCABC),
            scrim = Color(0xFF000000),
            inverseSurface = Color(0xFF2B322C),
            inverseOnSurface = Color(0xFFECF3E9),
            inversePrimary = Color(0xFF66DD8B),
            surfaceDim = Color(0xFFD5DCD2),
            surfaceBright = Color(0xFFF5FBF1),
            surfaceContainerLowest = Color(0xFFFFFFFF),
            surfaceContainerLow = Color(0xFFEFF6EC),
            surfaceContainer = Color(0xFFE9F0E6),
            surfaceContainerHigh = Color(0xFFE3EAE0),
            surfaceContainerHighest = Color(0xFFDEE4DB)
        )
}