package com.frost23z.bookshelf.ui.theme.colorscheme

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

/**
 * Nord is an arctic, north-bluish color palette created by Arctic Ice Studio.
 * It is a set of sixteen colors with light and dark modes.
 * https://www.nordtheme.com/docs/colors-and-palettes
 * M3 colors generated by Material Theme Builder (https://goo.gle/material-theme-builder-web)
 */

internal object NordColorScheme : ColorSchemeController() {
    override val darkScheme =
        darkColorScheme(
            primary = Color(0xFF88C0D0), // nord8
            onPrimary = Color(0xFF2E3440), // nord0
            primaryContainer = Color(0xFF88C0D0), // nord8
            onPrimaryContainer = Color(0xFF2E3440), // nord0
            inversePrimary = Color(0xFF397E91), // Muted nord8
            secondary = Color(0xFF81A1C1), // nord9
            onSecondary = Color(0xFF2E3440), // nord0
            secondaryContainer = Color(0xFF4C566A), // nord3
            onSecondaryContainer = Color(0xFF8FBCBB), // nord7
            tertiary = Color(0xFF5E81AC), // nord10
            onTertiary = Color(0xFF000000), // Pure black
            tertiaryContainer = Color(0xFF5E81AC), // nord10
            onTertiaryContainer = Color(0xFF000000), // Pure black
            background = Color(0xFF2E3440), // nord0
            onBackground = Color(0xFFECEFF4), // nord6
            surface = Color(0xFF2E3440), // nord0
            onSurface = Color(0xFFECEFF4), // nord6
            surfaceVariant = Color(0xFF3B4252), // nord1
            onSurfaceVariant = Color(0xFFD8DEE9), // nord4
            surfaceTint = Color(0xFF8FBCBB), // nord7
            outline = Color(0xFF616E88), // custom mix between nord2/3
            outlineVariant = Color(0xFF7B849B), // lighter custom outline
            error = Color(0xFFBF616A), // nord11
            onError = Color(0xFF2E3440), // nord0
            errorContainer = Color(0xFFBF616A), // nord11
            onErrorContainer = Color(0xFFECEFF4), // nord6
            scrim = Color(0xFF2E3440), // nord0
            inverseSurface = Color(0xFFECEFF4), // nord6
            inverseOnSurface = Color(0xFF2E3440), // nord0
            surfaceDim = Color(0xFF2E3440), // nord0
            surfaceBright = Color(0xFF434C5E), // nord2
            surfaceContainerLowest = Color(0xFF292E38), // darker nord0
            surfaceContainerLow = Color(0xFF2E3440), // nord0
            surfaceContainer = Color(0xFF3B4252), // nord1
            surfaceContainerHigh = Color(0xFF434C5E), // nord2
            surfaceContainerHighest = Color(0xFF4C566A), // nord3
        )

    override val lightScheme =
        lightColorScheme(
            primary = Color(0xFF5E81AC), // nord10
            onPrimary = Color(0xFF000000), // Pure black
            primaryContainer = Color(0xFF5E81AC), // nord10
            onPrimaryContainer = Color(0xFF000000), // Pure black
            inversePrimary = Color(0xFF8CA8CD), // Lighter nord10
            secondary = Color(0xFF81A1C1), // nord9
            onSecondary = Color(0xFF2E3440), // nord0
            secondaryContainer = Color(0xFF8FBCBB), // nord7
            onSecondaryContainer = Color(0xFF2E3440), // nord0
            tertiary = Color(0xFF88C0D0), // nord8
            onTertiary = Color(0xFF2E3440), // nord0
            tertiaryContainer = Color(0xFF88C0D0), // nord8
            onTertiaryContainer = Color(0xFF2E3440), // nord0
            error = Color(0xFFBF616A), // nord11
            onError = Color(0xFF2E3440), // nord0
            errorContainer = Color(0xFFBF616A), // nord11
            onErrorContainer = Color(0xFF2E3440), // nord0
            background = Color(0xFFECEFF4), // nord6
            onBackground = Color(0xFF2E3440), // nord0
            surface = Color(0xFFECEFF4), // nord6
            onSurface = Color(0xFF2E3440), // nord0
            surfaceVariant = Color(0xFFE5E9F0), // nord5
            onSurfaceVariant = Color(0xFF3B4252), // nord1
            surfaceTint = Color(0xFF88C0D0), // nord8
            outline = Color(0xFF4C566A), // nord3
            outlineVariant = Color(0xFF434C5E), // nord2
            surfaceContainerLowest = Color(0xFFF5F7FA), // lighter nord6
            surfaceContainerLow = Color(0xFFECEFF4), // nord6
            surfaceContainer = Color(0xFFE5E9F0), // nord5
            surfaceContainerHigh = Color(0xFFD8DEE9), // nord4
            surfaceContainerHighest = Color(0xFFCDD3DE), // custom darker nord4
        )
}