package com.frost23z.bookshelf.ui.theme.colorscheme

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

/**
 * Color scheme for Rosy Twilight theme.
 * Used Primary Color: #D31D42 with true to color inputs.
 * M3 colors generated by Material Theme Builder (https://goo.gle/material-theme-builder-web)
 */

internal object RosyTwilightColorScheme : ColorSchemeController() {
    override val darkScheme =
        darkColorScheme(
            primary = Color(0xFFFFB3B5),
            onPrimary = Color(0xFF680019),
            primaryContainer = Color(0xFFC70F3B),
            onPrimaryContainer = Color(0xFFFFFFFF),
            secondary = Color(0xFFFFB3B5),
            onSecondary = Color(0xFF65071A),
            secondaryContainer = Color(0xFF7B1A29),
            onSecondaryContainer = Color(0xFFFFC7C9),
            tertiary = Color(0xFFFFB787),
            onTertiary = Color(0xFF512400),
            tertiaryContainer = Color(0xFF9E4D00),
            onTertiaryContainer = Color(0xFFFFFFFF),
            error = Color(0xFFFFB4AB),
            onError = Color(0xFF690005),
            errorContainer = Color(0xFF93000A),
            onErrorContainer = Color(0xFFFFDAD6),
            background = Color(0xFF1E0F10),
            onBackground = Color(0xFFFADBDB),
            surface = Color(0xFF1E0F10),
            onSurface = Color(0xFFFADBDB),
            surfaceVariant = Color(0xFF5B4040),
            onSurfaceVariant = Color(0xFFE4BDBE),
            outline = Color(0xFFAB8889),
            outlineVariant = Color(0xFF5B4040),
            scrim = Color(0xFF000000),
            inverseSurface = Color(0xFFFADBDB),
            inverseOnSurface = Color(0xFF3E2C2C),
            inversePrimary = Color(0xFFBE0135),
            surfaceDim = Color(0xFF1E0F10),
            surfaceBright = Color(0xFF483435),
            surfaceContainerLowest = Color(0xFF190A0B),
            surfaceContainerLow = Color(0xFF271718),
            surfaceContainer = Color(0xFF2C1B1C),
            surfaceContainerHigh = Color(0xFF372526),
            surfaceContainerHighest = Color(0xFF433030)
        )

    override val lightScheme =
        lightColorScheme(
            primary = Color(0xFF950028),
            onPrimary = Color(0xFFFFFFFF),
            primaryContainer = Color(0xFFD31D42),
            onPrimaryContainer = Color(0xFFFFFFFF),
            secondary = Color(0xFFA43945),
            onSecondary = Color(0xFFFFFFFF),
            secondaryContainer = Color(0xFFFF8B92),
            onSecondaryContainer = Color(0xFF4D0010),
            tertiary = Color(0xFF753700),
            onTertiary = Color(0xFFFFFFFF),
            tertiaryContainer = Color(0xFFAC5400),
            onTertiaryContainer = Color(0xFFFFFFFF),
            error = Color(0xFFBA1A1A),
            onError = Color(0xFFFFFFFF),
            errorContainer = Color(0xFFFFDAD6),
            onErrorContainer = Color(0xFF410002),
            background = Color(0xFFFFF8F7),
            onBackground = Color(0xFF271718),
            surface = Color(0xFFFFF8F7),
            onSurface = Color(0xFF271718),
            surfaceVariant = Color(0xFFFFDADA),
            onSurfaceVariant = Color(0xFF5B4040),
            outline = Color(0xFF906F70),
            outlineVariant = Color(0xFFE4BDBE),
            scrim = Color(0xFF000000),
            inverseSurface = Color(0xFF3E2C2C),
            inverseOnSurface = Color(0xFFFFEDEC),
            inversePrimary = Color(0xFFFFB3B5),
            surfaceDim = Color(0xFFF1D3D3),
            surfaceBright = Color(0xFFFFF8F7),
            surfaceContainerLowest = Color(0xFFFFFFFF),
            surfaceContainerLow = Color(0xFFFFF0F0),
            surfaceContainer = Color(0xFFFFE9E9),
            surfaceContainerHigh = Color(0xFFFFE1E1),
            surfaceContainerHighest = Color(0xFFFADBDB)
        )
}