package com.frost23z.bookshelf.ui.theme.colorscheme

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

/**
 * Color scheme for Violet Haze theme.
 * Used Primary Color: #8A2BE2 with true to color inputs.
 * M3 colors generated by Material Theme Builder (https://goo.gle/material-theme-builder-web)
 */

internal object VioletHazeColorScheme : ColorSchemeController() {
    override val darkScheme =
        darkColorScheme(
            primary = Color(0xFFDCB8FF),
            onPrimary = Color(0xFF480081),
            primaryContainer = Color(0xFF811CD9),
            onPrimaryContainer = Color(0xFFFFFFFF),
            secondary = Color(0xFFDCB8FF),
            onSecondary = Color(0xFF43196D),
            secondaryContainer = Color(0xFF532B7D),
            onSecondaryContainer = Color(0xFFE6CAFF),
            tertiary = Color(0xFFFFAEDA),
            onTertiary = Color(0xFF610047),
            tertiaryContainer = Color(0xFFAD0382),
            onTertiaryContainer = Color(0xFFFFFFFF),
            error = Color(0xFFFFB4AB),
            onError = Color(0xFF690005),
            errorContainer = Color(0xFF93000A),
            onErrorContainer = Color(0xFFFFDAD6),
            background = Color(0xFF16111B),
            onBackground = Color(0xFFEADFEE),
            surface = Color(0xFF16111B),
            onSurface = Color(0xFFEADFEE),
            surfaceVariant = Color(0xFF4C4354),
            onSurfaceVariant = Color(0xFFCFC2D7),
            outline = Color(0xFF988CA0),
            outlineVariant = Color(0xFF4C4354),
            scrim = Color(0xFF000000),
            inverseSurface = Color(0xFFEADFEE),
            inverseOnSurface = Color(0xFF342E39),
            inversePrimary = Color(0xFF8422DC),
            surfaceDim = Color(0xFF16111B),
            surfaceBright = Color(0xFF3D3742),
            surfaceContainerLowest = Color(0xFF110C16),
            surfaceContainerLow = Color(0xFF1F1924),
            surfaceContainer = Color(0xFF231D28),
            surfaceContainerHigh = Color(0xFF2E2832),
            surfaceContainerHighest = Color(0xFF39323D)
        )

    override val lightScheme =
        lightColorScheme(
            primary = Color(0xFF7100C5),
            onPrimary = Color(0xFFFFFFFF),
            primaryContainer = Color(0xFF993FF1),
            onPrimaryContainer = Color(0xFFFFFFFF),
            secondary = Color(0xFF744B9F),
            onSecondary = Color(0xFFFFFFFF),
            secondaryContainer = Color(0xFFD7AEFF),
            onSecondaryContainer = Color(0xFF441A6D),
            tertiary = Color(0xFF95006F),
            onTertiary = Color(0xFFFFFFFF),
            tertiaryContainer = Color(0xFFCB2C9A),
            onTertiaryContainer = Color(0xFFFFFFFF),
            error = Color(0xFFBA1A1A),
            onError = Color(0xFFFFFFFF),
            errorContainer = Color(0xFFFFDAD6),
            onErrorContainer = Color(0xFF410002),
            background = Color(0xFFFFF7FF),
            onBackground = Color(0xFF1F1924),
            surface = Color(0xFFFFF7FF),
            onSurface = Color(0xFF1F1924),
            surfaceVariant = Color(0xFFECDEF3),
            onSurfaceVariant = Color(0xFF4C4354),
            outline = Color(0xFF7E7386),
            outlineVariant = Color(0xFFCFC2D7),
            scrim = Color(0xFF000000),
            inverseSurface = Color(0xFF342E39),
            inverseOnSurface = Color(0xFFF8EDFC),
            inversePrimary = Color(0xFFDCB8FF),
            surfaceDim = Color(0xFFE1D6E5),
            surfaceBright = Color(0xFFFFF7FF),
            surfaceContainerLowest = Color(0xFFFFFFFF),
            surfaceContainerLow = Color(0xFFFBF0FF),
            surfaceContainer = Color(0xFFF5EAF9),
            surfaceContainerHigh = Color(0xFFF0E5F3),
            surfaceContainerHighest = Color(0xFFEADFEE)
        )
}
